#!/usr/bin/env sh

#
# colors
#
transparent_color="0x00000000"

# tokyonight-night
# bar_color=0xff1a1b26
# default_icon_color="0xffc0caf5"
# icon_highlight_color="0xffbb9af7"
# default_label_color="0xffc0caf5"

# onedark-deep
bar_color="0xff1a212e"
bar_border_color="0xff41a7fc"
default_label_color="0xff93a4c3"
default_icon_color="0xff93a4c3"
icon_highlight_color="0xffc75ae8"
bracket_hightlight_color="0xff862aa1"
danger_color="0xff992525"
item_background_color="0xcc000000" # Semi-transparent black background for items

#
# fonts
#
default_icon_font="Font Awesome 6 Free:Regular:16.0"
default_label_font="JetBrainsMono Nerd Font Mono:Bold:18.0"
brand_font="JetBrainsMono Nerd Font Mono :Regular:16.0"
# duotone_font="Font Awesome 6 Duotone:Solid:14.0"

#
# variables
#
plugins="$HOME/.config/sketchybar/plugins"
# For aerospace, you can manually set this based on your monitor setup
display_count="1" # Change to "2" if you have two monitors

############## BAR ##############
sketchybar --bar \
  border_color=${bar_border_color} \
  border_width=0 \
  corner_radius=8 \
  color=${transparent_color} \
  height=30 \
  margin=8 \
  padding_left=10 \
  padding_right=10 \
  position=top \
  shadow=off \
  y_offset=4

# ############## DEFAULTS ###############
sketchybar --default \
  cache_scripts=on \
  icon.color="${default_icon_color}" \
  icon.font="${default_icon_font}" \
  icon.highlight_color="${icon_highlight_color}" \
  icon.padding_left=3 \
  icon.padding_right=3 \
  icon.y_offset=-1 \
  label.color="${default_label_color}" \
  label.font="${default_label_font}" \
  label.padding_left=3 \
  label.padding_right=5 \
  label.y_offset=-1 \
  background.color="${item_background_color}" \
  background.corner_radius=8 \
  background.height=28 \
  background.padding_left=4 background.padding_right=4 updates=when_shown

############## AEROSPACE WORKSPACES ###############
sketchybar --add event aerospace_workspace_change

# Add first separator
sketchybar --add item space.separator.0 left \
  --set space.separator.0 \
  label="|" \
  label.color="${default_label_color}" \
  background.color="${transparent_color}" \
  icon=""

for i in $(seq 1 10); do
  sketchybar \
    --add item space.$i left \
    --set space.$i \
    label="$i" \
    icon="" \
    background.color="${transparent_color}" \
    script="$plugins/aerospace.sh" \
    click_script="aerospace workspace $i" \
    --subscribe space.$i aerospace_workspace_change

  # Add separator after each workspace
  sketchybar --add item space.separator.$i left \
    --set space.separator.$i \
    label="|" \
    label.color="${default_label_color}" \
    background.color="${transparent_color}" \
    icon=""
done

# Trigger initial update
sketchybar --trigger aerospace_workspace_change

sketchybar \
  --add bracket spaces_bracket \
  space.separator.0 \
  space.1 space.separator.1 \
  space.2 space.separator.2 \
  space.3 space.separator.3 \
  space.4 space.separator.4 \
  space.5 space.separator.5 \
  space.6 space.separator.6 \
  space.7 space.separator.7 \
  space.8 space.separator.8 \
  space.9 space.separator.9 \
  space.10 space.separator.10 \
  --set spaces_bracket \
  background.color="${item_background_color}" \
  background.padding_right=4 \
  background.padding_left=4 \
  background.corner_radius=6

# ################# RIGHT ITEMS ####################
sketchybar \
  --add item time right \
  --set time \
  label.color=0xffF19E38 \
  update_freq=30 \
  script="${plugins}/time.sh" \
  --add item time_spacer right \
  --set time_spacer \
  label=" " \
  background.color="${transparent_color}" \
  --add item weather right \
  --set weather \
  update_freq=1800 \
  script="${plugins}/weather_v2.sh" \
  click_script="open https://wttr.in/Tbilisi" \
  --add item github.issues right \
  --set github.issues \
  label="󰠗 0" \
  popup.background.color="${bar_color}" \
  popup.background.border_color="${bar_border_color}" \
  popup.background.border_width=1 \
  popup.background.corner_radius=8 \
  click_script="${plugins}/github_issues_popup.sh" \
  --add item github.reviews right \
  --set github.reviews \
  label="󰄬 0" \
  popup.background.color="${bar_color}" \
  popup.background.border_color="${bar_border_color}" \
  popup.background.border_width=1 \
  popup.background.corner_radius=8 \
  click_script="${plugins}/github_review_popup.sh" \
  --add item github.prs right \
  --set github.prs \
  label="󰊢 0" \
  popup.background.color="${bar_color}" \
  popup.background.border_color="${bar_border_color}" \
  popup.background.border_width=1 \
  popup.background.corner_radius=8 \
  click_script="${plugins}/github_pr_popup.sh" \
  --add item github.label right \
  --set github.label \
  label="git:" \
  --add item github_stats right \
  --set github_stats \
  drawing=off \
  update_freq=300 \
  script="${plugins}/github_stats_interactive.sh" \
  --add item cpu right \
  --set cpu \
  icon=􀧓 \
  update_freq=5 \
  script="${plugins}/cpu.sh" \
  click_script="open -a activity\ monitor" \
  --add item battery right \
  --set battery \
  update_freq=10 \
  script="${plugins}/battery.sh" \
  --add item input_source right \
  --set input_source \
  update_freq=1 \
  script="${plugins}/input_source.sh" \
  --add item meet right \
  --set meet \
  icon.font="${brand_font}" \
  update_freq=1 \
  script="${plugins}/meet.sh" \
  click_script="${plugins}/meet-mute-toggle.sh"

sketchybar \
  --add bracket clock_bracket \
  time \
  --set clock_bracket \
  background.color="${transparent_color}" \
  --add bracket utility_bracket \
  weather \
  github.label \
  github.prs \
  github.reviews \
  github.issues \
  cpu \
  battery \
  input_source \
  --set utility_bracket \
  background.color="${transparent_color}"

###################### CENTER ITEMS ###################
# Always show window title
sketchybar \
  --add event window_focus \
  --add event title_change \
  --add item window_title center \
  --set window_title \
  icon="" \ \
  script="$plugins/window_title.sh" \
  --subscribe window_title \
  window_focus \
  front_app_switched \
  space_change \
  title_change \
  aerospace_workspace_change
# fi

sketchybar \
  --add bracket center \
  window_title \
  --set center \
  background.color="${transparent_color}"

###################### FINALIZE ###################
sketchybar -m --update

echo "sketchybar configuration loaded.."

exit 0
